# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\hanfi\OneDrive\Desktop\MyBot\gui\GuiMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# ################################################################
#  E L T E R N K L A S S E
# ################################################################
# imports
from PyQt5 import QtCore, QtGui, QtWidgets

# Klasse

class Ui_MainWindow(object):

    def __init__(self, MainWindow):
        self.setupUi(MainWindow)

    def setupUi(self, MainWindow):


        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(938, 798)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 350, 311, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(30, 320, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(490, 320, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 350, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 400, 47, 13))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 320, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 320, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(540, 320, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(630, 320, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(490, 350, 311, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(810, 350, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 30, 431, 281))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(490, 30, 431, 281))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_3.setGeometry(QtCore.QRect(30, 450, 881, 291))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(120, 0, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(580, 0, 131, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 0, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 0, 91, 21))
        self.label_2.setObjectName("label_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(370, 410, 151, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.ltloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.ltloadButton.setGeometry(QtCore.QRect(390, 0, 75, 23))
        self.ltloadButton.setObjectName("ltloadButton")
        self.rtLoadButton = QtWidgets.QPushButton(self.centralwidget)
        self.rtLoadButton.setGeometry(QtCore.QRect(850, 0, 75, 23))
        self.rtLoadButton.setObjectName("rtLoadButton")
        self.pushOkay = QtWidgets.QPushButton(self.centralwidget)
        self.pushOkay.setGeometry(QtCore.QRect(530, 410, 75, 23))
        self.pushOkay.setObjectName("pushOkay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 938, 21))
        self.menubar.setObjectName("menubar")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuNew.addAction(self.actionNew)
        self.menuNew.addAction(self.actionOpen)
        self.menuNew.addAction(self.actionSave)
        self.menubar.addAction(self.menuNew.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.rtLoadButton.clicked.connect(self.pressedRLB)
        self.ltloadButton.clicked.connect(self.pressedLLB)
        self.pushOkay.clicked.connect(self.pressedOkay)
        self.index = "todo"
        self.pushButton_2.clicked.connect(self.pressedEinfL)

# funktionen

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Einfügen"))
        self.label_3.setText(_translate("MainWindow", "Ergebnis"))
        self.pushButton_2.setText(_translate("MainWindow", "Entfernen"))
        self.pushButton_3.setText(_translate("MainWindow", "Bearbeiten"))
        self.pushButton_4.setText(_translate("MainWindow", "Entfernen"))
        self.pushButton_5.setText(_translate("MainWindow", "Bearbeiten"))
        self.pushButton_6.setText(_translate("MainWindow", "Einfügen"))
        self.label.setText(_translate("MainWindow", "Tabel auswählen:"))
        self.label_2.setText(_translate("MainWindow", "Tabel auswählen:"))
        self.ltloadButton.setText(_translate("MainWindow", "LTLoad"))
        self.rtLoadButton.setText(_translate("MainWindow", "RTLoad"))
        self.pushOkay.setText(_translate("MainWindow", "Okay"))
        self.menuNew.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))


    def pressedLLB(self):
        self.index = str(self.comboBox.currentText())

    def pressedRLB(self):
        self.index = str(self.comboBox.currentText())

    def pressedOkay(self):
        print("okay wird gedrück")

    def pressedEinfL(self):
        self.auswahl1 = self.spinBox.value()
        print(self.auswahl1)

    def pressedEinfR(self):
        self.auswahl2 = self.spinBox_2.value()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

